spring.datasource.url=jdbc:mysql://localhost:3306/excercise201?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.rubilia.exercise201=DEBUG
spring.data.rest.enabled=false
Uploads.directory=./Uploads/
file.upload-dir=./Uploads/

# Google OAuth2
# spring.security.oauth2.client.registration.google.client-id=895523100356-61rs7diftkjnb5soq4r6kt5rpvmgf7mb.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thieb27032004@gmail.com
spring.mail.password=dnvw nbzk hfrn mpzi
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true